name: redoperator
favicon: null
layout_spectrum: 0.23283
typography_spectrum: 0.30989
title: RED Operator » RED + Steadicam Operator - Lucas Tucknott
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#191f2b'
    - '#3f4f57'
    - '#566767'
    - '#959783'
    - '#cfcdb9'
  brandStrength: 0.3125
  lightness: 0.8125
  saturation: 0.9997610924765468
  rhythmicContrast: 0.8401811798103154
purpose: []
