name: redoperator
favicon: null
layout_spectrum: 0.79178556217812
typography_spectrum: 0.7898614259902388
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.32073142449371517
  lightness: 0.8798160769511014
  saturation: 0.9997610924765468
  rhythmicContrast: 0.8401811798103154
purpose: []
